version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Preprocess data
          command: |
            . venv/bin/activate
            python preprocess.py
      - run:
          name: Train model
          command: |
            . venv/bin/activate
            python train.py
      - run:
          name: Make predictions
          command: |
            . venv/bin/activate
            python predict.py
      - persist_to_workspace:
          root: .
          paths:
            - models/*

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
